name: 'Config entity example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
# core: 8.x
dependencies:
  - examples:examples

# Information added by Drupal.org packaging script on 2017-03-15
version: '8.x-1.x-dev'
core: '8.x'
project: 'examples'
datestamp: 1489606986
